---
meta:
  name:    librdkafka
  target:  pipes@cfcommunity
  url:     https://pipes.starkandwayne.com

  git:
    email:  ((git-commit-email))
    name:   'Stark & Wayne CI Bot'

  aws:
    bucket:      (( grab meta.pipeline ))
    region_name: us-east-1
    access_key:  ((aws-cfcommunity.access))
    secret_key:  ((aws-cfcommunity.secret))

  github:
    owner:  starkandwayne
    repo:   (( concat meta.name "-buildpack" ))
    branch: master
    private_key:  ((github-private-key))
    access_token: ((github-access-token))

  slack:
    webhook:       ((slack.webhook))
    username:      ((slack.username))
    icon:          ((slack.icon))
    channel:       "#starkandwayne-buildpacks"

resources:
  - name: librdkafka
    type: github-release
    source:
      user: edenhill
      repository: librdkafka
      access_token: (( grab meta.github.access_token ))

  - name: compiled-blob
    type: s3
    source:
      bucket: (( grab meta.aws.bucket ))
      region_name: (( grab meta.aws.region_name ))
      access_key_id: (( grab meta.aws.access_key ))
      secret_access_key: (( grab meta.aws.secret_key ))
      regexp: blobs/librdkafka/librdkafka-compiled-(.*).tgz
